# Mapping for calling column names of the various input dataframes
TRACE = 'Trace'
TRACE_NUMBER = 'TraceNumber'
SCENARIO = 'Scenario'
LF_ANNUAL = 'LF_Annual'
DEMAND = 'demand'
INIT_STORAGE = 'InitCombinedStorage'
YEAR = 'Year'
MEDIAN_FLOW = 'Median'
MAX_ANNUAL_FLOW = 'Max'
MIN_ANNUAL_FLOW = 'Min'
IQR_FLOW = 'IQR'
MEDIAN_LESS_DEMAND = 'MedianLessDemand'
NEURON = 'Neuron'
SOW = 'SOW'
POLICY = 'Policy'
OBJECTIVE = 'Objective'
